### ISSUE TITLE
HTTPS support?

### ISSUE THREAD

**Issue by althe3rd** [gtracy/madison-transit-api#19]
It appears that all the API calls occur through http and that the api server doesn't appear to respond to https calls.  Is there any plans or option for those of us starting to run sites as full https?  Most of the modern browsers these days won't allow http calls through when the origin site is https.

Thanks!

**Comment by gtracy** [comment]
you're right. 

the service runs on GAE. when it first launched, it didn't support SSL on custom domains. i'm going to take a closer look now and see how i can turn that on.

thanks.

**Comment by gtracy** [comment]
wow. they made that really easy.

thanks for the poke on this @althe3rd!
